# Generated by Django 4.2.11 on 2024-12-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
